spring:
  application:
    name: Spring Boot Demo Project
  profiles:
    active: store1
  datasource:
    url: "jdbc:postgresql://localhost:5432/products"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      uri: ${mongodb-uri}
      database: "product_reviews"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-sender}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-d8rm3bg4cwywnjin.eu.auth0.com/

mail:
  sender:
    username: ${mail-sender}

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
